config/routes.rb
ParliamentaryQuestions::Application.routes.draw do
  get 'ping'               => 'ping#index'
  get 'healthcheck'        => 'health_check#index'

  get 'statistics/'                 => 'statistics#index'
  get 'statistics/stages_time'      => 'statistics#stages_time'
  get 'statistics/on_time'          => 'statistics#on_time'
  get 'statistics/time_to_assign'   => 'statistics#time_to_assign'
  get 'statistics/ao_response_time' => 'statistics#ao_response_time'
  get 'statistics/ao_churn'         => 'statistics#ao_churn'
  get 'metrics_dashboard/'          => 'metrics_dashboard#index'
  get 'gecko_report'                => 'gecko_report#index'

  resources :minister_contacts
  get 'minister_contacts/new/:id' => 'minister_contacts#new', :as => :new_minister_contact_withid

  resources :ogds
  get 'find_ogd' => 'ogds#find'

  resources :press_desks

  resources :press_officers

  resources :progresses

  resources :ministers

  resources :deputy_directors

  resources :divisions

  resources :directorates

  resources :watchlist_members

  resources :early_bird_members

  resources :actionlist_members

  resources :action_officers

  devise_for :users, :controllers => { :invitations => 'users/invitations', sessions: 'users/sessions' }
  resources  :users

  resources :pqs, only: [ :index, :show, :update ]

  resources :trim_links

  get 'trim_links/new/:id' => 'trim_links#new'

  get 'admin' => 'admin#index'

  get 'commission/:id'               => 'commission#commission'
  get 'commission_complete/:id'      => 'commission#complete'
  get 'commission_reject_manual/:id' => 'manual_reject_commission#reject_manual'
  post 'commission'                  => 'commission#commission', as: :commission

  get 'quick_action_export'     => 'quick_action_export#new'
  post 'quick_action_export' => 'quick_action_export#new'
  get 'quick_action_export/export' => 'quick_action_export#export'

  get '/', to: 'root#index', as: :root
  get 'dashboard'             => 'dashboard#index'
  get 'dashboard/in_progress' => 'dashboard#in_progress'
  get 'dashboard/backlog' => 'dashboard#backlog'

  get 'search' => 'search#index'

  get 'filter'         => 'filter#index'
  get 'filter/:search' => 'filter#index'

  get 'dashboard/search'          => 'dashboard#search'
  post 'dashboard/search/:search' => 'dashboard#search'

  get 'dashboard/by_status/:qstatus'             => 'dashboard#by_status', as: :dashboard_by_status
  get 'dashboard/in_progress_by_status/:qstatus' => 'dashboard#in_progress_by_status', as: :dashboard_in_progress_by_status
  get 'dashboard/transferred'                    => 'dashboard#transferred', as: :dashboard_transferred
  get 'dashboard/i_will_write'                   => 'dashboard#i_will_write', as: :dashboard_iww

  get 'assignment/:uin'  => 'assignment#show', as: :assignment
  post 'assignment/:uin' => 'assignment#create'

  get 'watchlist/dashboard'   => 'watchlist_dashboard#index'
  get 'watchlist/preview'     => 'watchlist_dashboard#preview'
  get 'watchlist/send_emails' => 'watchlist_send_emails#send_emails'

  get 'early_bird/dashboard'   => 'early_bird_dashboard#index'
  get 'early_bird/preview'     => 'early_bird_dashboard#preview'
  get 'early_bird/send_emails' => 'early_bird_send_emails#send_emails'

  #get 'preview' => 'preview#index'

  get 'find_action_officers' => 'action_officers#find'

  get 'finance/questions' => 'finance#questions'
  post 'finance/confirm'  => 'finance#confirm'

  get 'transferred/new'     => 'transferred#new'
  post 'transferred/create' => 'transferred#create'

  get 'i_will_write/create' => 'i_will_write#create'

  get 'send_accept_reject_reminder/:id' => 'action_officer_reminder#accept_reject'
  get 'send_draft_reminder/:id'         => 'action_officer_reminder#send_draft'

  match 'export/pq.csv' => 'export#csv', via: [:get, :post]
  get 'export'          => 'export#index'

  match 'export_pod/pq_pod.csv' => 'export#csv_for_pod', via: [:get, :post]
  get 'export_pod'              => 'export#index_for_pod'

  match 'export/csv_quick.csv' => 'export#csv_quick', via: [:get, :post]
  get 'export'          => 'export#index'

  get 'reports/ministers_by_progress'  => 'reports#ministers_by_progress'
  get 'reports/press_desk_by_progress' => 'reports#press_desk_by_progress'
  match 'reports/filter_all'           => 'reports#filter_all', via: [:get, :post], as: 'filter_all'
  if Rails.env.development?
    mount_rails_db_info as: 'rails_db_info_engine'
    # mount_rails_db_info is enough for rails version < 4
  end
  match "*path", to: "application#page_not_found", via: :all

  if Rails.env.production?
    get '401', :to => 'application#unauthorized'
    get '404', :to => 'application#page_not_found'
    get '500', :to => 'application#server_error'
  end
end

app/models/early_bird_member.rb
class EarlyBirdMember < ActiveRecord::Base
  extend  SoftDeletion::Collection
  include SoftDeletion::Record

  has_paper_trail
  validates :name, presence: true
  validates :email, presence: true, uniqueness: true, on: :create
  validates_format_of :email,:with => Devise::email_regexp

	before_validation Validators::Whitespace.new
end

app/controllers/early_bird_members_controller.rb
class EarlyBirdMembersController < ApplicationController
  before_action :authenticate_user!, PQUserFilter

  def index
    @early_bird_members = EarlyBirdMember.all.order('lower(name)')
    update_page_title('Early bird members')
  end

  def show
    loading_earlybird_member
    update_page_title('Early bird member details')
  end

  def edit
    loading_earlybird_member
    update_page_title('Edit early bird member')
  end

  def update
    loading_earlybird_member do
      if @early_bird_member.update(early_bird_member_params)
        flash[:success] = 'Early bird member was successfully updated.'
        redirect_to @early_bird_member
      else
        render action: 'edit'
      end
    end
  end

  def new
    @early_bird_member = EarlyBirdMember.new
    update_page_title('Add early bird member')
  end

  def create
    @early_bird_member = EarlyBirdMember.new(early_bird_member_params)

    if @early_bird_member.save
      flash[:success] = 'Early bird member was successfully created.'
      redirect_to @early_bird_member
    else
      render action: 'new'
    end
  end

  private

  def loading_earlybird_member
    @early_bird_member = EarlyBirdMember.find(params[:id])
    yield if block_given?
  end

  def early_bird_member_params
    params.require(:early_bird_member).permit(:name, :email, :deleted)
  end
end

app/views/early_bird_members/_form.html.slim
#admin-wl-form
  = form_for @early_bird_member do |f|
    = render partial: 'shared/errors', object: @early_bird_member
    - if @early_bird_member.errors.any?
    fieldset
      .form-group
        label.form-label for="early_bird_member_name"  Name
        = f.text_field :name, {class: 'form-control'}
      .form-group
        label.form-label for="early_bird_member_email"  Email
        = f.email_field :email , {class: 'form-control'}
      p.text Status
      .form-group
        label.block-label for="early_bird_member_deleted"
          = f.check_box :deleted
          | Inactive
      .form-group
        = f.submit 'Save', :id => 'save', :class => 'button'

app/views/early_bird_members/edit.html.slim
h1 Edit early bird member
= render 'form'
= link_to 'Return to early bird member list', early_bird_members_path, {class: 'admin-link'}

app/views/early_bird_members/index.html.slim
= render partial: "shared/flash_messages", flash: flash
h1 Early bird members
#admin-wm-list
  div class="row"
    ul#admin-button-bar
      li= link_to ('Send early bird info'), {controller: 'early_bird_send_emails', action: 'send_emails'}, {class: 'button', :onclick=> "ga('send', 'event', 'settings', 'earlybird', 'send early bird info');" }
      li= link_to ('Add early bird member'), new_early_bird_member_path, {class: 'button-secondary'}
      li= link_to ('Early bird preview'), {controller: 'early_bird_dashboard', action: 'preview'}, {class: 'button-secondary'}
  table.table
    thead
      tr
        th Name
        th Email
        th#admin-status Status
        th
    tbody
      - @early_bird_members.each do |early_bird_member|
        tr
          td= link_to early_bird_member.name, early_bird_member_path(early_bird_member)
          td= early_bird_member.email
          td= render partial: 'shared/status', object: early_bird_member
          td.edit= link_to 'Edit', edit_early_bird_member_path(early_bird_member)

app/views/early_bird_members/new.html.slim
h1 Add early bird member
= render 'form'
= link_to 'Return to early bird member list', early_bird_members_path, {class: 'admin-link'}

app/views/early_bird_members/show.html.slim
h1 Early bird member details
#admin-wl-details
  = render partial: "shared/flash_messages", flash: flash
  h2 Name
  p.text= @early_bird_member.name
  h2 Email
  p.text= @early_bird_member.email
  h2 Status
  = render partial: 'shared/status', object: @early_bird_member
  = link_to 'Edit', edit_early_bird_member_path(@early_bird_member), {class: 'admin-link'}
  = link_to 'Return to early bird member list', early_bird_members_path, {class: 'admin-link'}