config/routes.rb
ParliamentaryQuestions::Application.routes.draw do
  get 'ping'               => 'ping#index'
  get 'healthcheck'        => 'health_check#index'

  get 'statistics/'                 => 'statistics#index'
  get 'statistics/stages_time'      => 'statistics#stages_time'
  get 'statistics/on_time'          => 'statistics#on_time'
  get 'statistics/time_to_assign'   => 'statistics#time_to_assign'
  get 'statistics/ao_response_time' => 'statistics#ao_response_time'
  get 'statistics/ao_churn'         => 'statistics#ao_churn'
  get 'metrics_dashboard/'          => 'metrics_dashboard#index'
  get 'gecko_report'                => 'gecko_report#index'

  resources :minister_contacts
  get 'minister_contacts/new/:id' => 'minister_contacts#new', :as => :new_minister_contact_withid

  resources :ogds
  get 'find_ogd' => 'ogds#find'

  resources :press_desks

  resources :press_officers

  resources :progresses

  resources :ministers

  resources :deputy_directors

  resources :divisions

  resources :directorates

  resources :watchlist_members

  resources :early_bird_members

  resources :actionlist_members

  resources :action_officers

  devise_for :users, :controllers => { :invitations => 'users/invitations', sessions: 'users/sessions' }
  resources  :users

  resources :pqs, only: [ :index, :show, :update ]

  resources :trim_links

  get 'trim_links/new/:id' => 'trim_links#new'

  get 'admin' => 'admin#index'

  get 'commission/:id'               => 'commission#commission'
  get 'commission_complete/:id'      => 'commission#complete'
  get 'commission_reject_manual/:id' => 'manual_reject_commission#reject_manual'
  post 'commission'                  => 'commission#commission', as: :commission

  get 'quick_action_export'     => 'quick_action_export#new'
  post 'quick_action_export' => 'quick_action_export#new'
  get 'quick_action_export/export' => 'quick_action_export#export'

  get '/', to: 'root#index', as: :root
  get 'dashboard'             => 'dashboard#index'
  get 'dashboard/in_progress' => 'dashboard#in_progress'
  get 'dashboard/backlog' => 'dashboard#backlog'

  get 'search' => 'search#index'

  get 'filter'         => 'filter#index'
  get 'filter/:search' => 'filter#index'

  get 'dashboard/search'          => 'dashboard#search'
  post 'dashboard/search/:search' => 'dashboard#search'

  get 'dashboard/by_status/:qstatus'             => 'dashboard#by_status', as: :dashboard_by_status
  get 'dashboard/in_progress_by_status/:qstatus' => 'dashboard#in_progress_by_status', as: :dashboard_in_progress_by_status
  get 'dashboard/transferred'                    => 'dashboard#transferred', as: :dashboard_transferred
  get 'dashboard/i_will_write'                   => 'dashboard#i_will_write', as: :dashboard_iww

  get 'assignment/:uin'  => 'assignment#show', as: :assignment
  post 'assignment/:uin' => 'assignment#create'

  get 'watchlist/dashboard'   => 'watchlist_dashboard#index'
  get 'watchlist/preview'     => 'watchlist_dashboard#preview'
  get 'watchlist/send_emails' => 'watchlist_send_emails#send_emails'

  get 'early_bird/dashboard'   => 'early_bird_dashboard#index'
  get 'early_bird/preview'     => 'early_bird_dashboard#preview'
  get 'early_bird/send_emails' => 'early_bird_send_emails#send_emails'

  #get 'preview' => 'preview#index'

  get 'find_action_officers' => 'action_officers#find'

  get 'finance/questions' => 'finance#questions'
  post 'finance/confirm'  => 'finance#confirm'

  get 'transferred/new'     => 'transferred#new'
  post 'transferred/create' => 'transferred#create'

  get 'i_will_write/create' => 'i_will_write#create'

  get 'send_accept_reject_reminder/:id' => 'action_officer_reminder#accept_reject'
  get 'send_draft_reminder/:id'         => 'action_officer_reminder#send_draft'

  match 'export/pq.csv' => 'export#csv', via: [:get, :post]
  get 'export'          => 'export#index'

  match 'export_pod/pq_pod.csv' => 'export#csv_for_pod', via: [:get, :post]
  get 'export_pod'              => 'export#index_for_pod'

  match 'export/csv_quick.csv' => 'export#csv_quick', via: [:get, :post]
  get 'export'          => 'export#index'

  get 'reports/ministers_by_progress'  => 'reports#ministers_by_progress'
  get 'reports/press_desk_by_progress' => 'reports#press_desk_by_progress'
  match 'reports/filter_all'           => 'reports#filter_all', via: [:get, :post], as: 'filter_all'
  if Rails.env.development?
    mount_rails_db_info as: 'rails_db_info_engine'
    # mount_rails_db_info is enough for rails version < 4
  end
  match "*path", to: "application#page_not_found", via: :all

  if Rails.env.production?
    get '401', :to => 'application#unauthorized'
    get '404', :to => 'application#page_not_found'
    get '500', :to => 'application#server_error'
  end
end

app/views/shared/_allocation_list.html.slim
- if ao_pq.accepted?
  = ao_pq.action_officer.name
  |  (#{ao_pq.action_officer.deputy_director.division.name}) 
  span.flag.accepted Accepted
- elsif ao_pq.rejected?
  div.reveal
    span.link.closed aria-controls="rejection-#{ao_pq.id}-#{ao_pq.action_officer.id}"
      = ao_pq.action_officer.name
      |  (#{ao_pq.action_officer.deputy_director.division.name}) 
      span.flag.rejected Rejected
    .panel-indent.closed id="rejection-#{ao_pq.id}-#{ao_pq.action_officer.id}"
      p.strong= ao_pq.reason_option
      p= ao_pq.reason
- else
    = ao_pq.action_officer.name
    |  (#{ao_pq.action_officer.deputy_director.division.name}) 
    span.flag.no-response No response

app/views/shared/_answer_time.html.slim
- if date_for_answer && is_closed
  - from_time = DateTime.now.change ({:offset => 0})
  - from_time = from_time.beginning_of_day()
  - overdue = (from_time -  date_for_answer.to_datetime) > 0
  - if overdue
    = render 'shared/warning_icon'

app/views/shared/_ao_reminder_link.html.slim
- if ao_pq.accepted?
  - reminder_draft_count =  ao_pq.reminder_draft > 0 ? " (#{ao_pq.reminder_draft})" : ''
  = link_to raw("<span class=\"fa fa-envelope-o\"></span> Draft reminder#{reminder_draft_count}"), {controller: 'action_officer_reminder', action: 'send_draft', id: ao_pq.id, remote: true}, {class: 'ao-reminder-link', title: 'Send a reminder email to do the draft'}
- elsif ao_pq.rejected?
  /! rejected
- else
  - reminder_accept_count =  ao_pq.reminder_accept > 0 ? " (#{ao_pq.reminder_accept})" : ''
  = link_to raw("<span class=\"fa fa-envelope-o\"></span> Send reminder#{reminder_accept_count}"), {controller: 'action_officer_reminder', action: 'accept_reject', id: ao_pq.id, remote: true}, {class: 'ao-reminder-link', title: 'Send an accept/reject reminder email'}

app/views/shared/_commissioned.html.slim
.pq-msg-success.fade.in
  = @pq.uin
  | commissioned successfully
  button.close data-dismiss="alert"  x

app/views/shared/_deadline_time.html.slim
- if internal_deadline && !is_closed && draft_reply.blank?
  - deadline_uk = Time.find_zone('London').parse(internal_deadline.to_s).to_datetime
  - if deadline_uk < DateTime.now
    = render 'shared/warning_icon'

app/views/shared/_errors.html.slim
- name = errors.class.model_name.human
- errors = errors.errors
- if errors.any?
  .pq-msg-error
    = "#{pluralize(errors.count, "error")} prohibited this #{name} from being saved:"
    ul
      - errors.full_messages.each do |msg|
        li= msg

app/views/shared/_flash_messages.html.slim
- flash.each do |type, message|
  - if !message.blank?
    div class=("#{flash_class_for(type)} fade in") 
      = message
      button.close data-dismiss="alert"  x
- flash.clear

app/views/shared/_minister_selection.html.slim
.minister-dropdown.form-group id="answering-minister-form-#{question.try(:id)}"
  label.form-label for="commission_form_minister_id" Answering minister
  = form.collection_select(:minister_id, Minister.active_or_having_id(question.minister_id), :id, :name_with_inactive_status, { :include_blank => ''}, { class: 'minister-select required-for-commission'})
  = render('shared/warning_icon') if minister_warning?(question, question.try(:minister))

.minister-dropdown.form-group id="policy-minister-form-#{question.try(:id)}"
  label.form-label for="pq_policy_minister_id" Policy minister (Optional)
  = form.collection_select(:policy_minister_id, Minister.active_or_having_id(question.policy_minister_id), :id, :name_with_inactive_status, { :include_blank => ''}, { class: ' minister-select' })
  = render('shared/warning_icon') if minister_warning?(question, question.try(:policy_minister))

app/views/shared/_navigation.html.slim
- if user_signed_in?
  nav.navbar.navbar-default role="navigation"
    .container-fluid
      .navbar-header
        button.navbar-toggle data-target=".navbar-collapse" data-toggle="collapse" type="button"
          span.sr-only Toggle navigation
          span.icon-bar
          span.icon-bar
          span.icon-bar
      .collapse.navbar-collapse
        - if current_user.pq_user?
          ul.nav.navbar-nav
            li class=('active' if @dashboard_state == 'New')
              = link_to 'New', dashboard_path, action: 'index'
            li class=('active' if @dashboard_state == 'In progress')
              = link_to 'In progress', dashboard_in_progress_path, action: 'in_progress'
            li class=('active' if @dashboard_state == 'Backlog')
              = link_to 'Backlog', dashboard_backlog_path, action: 'backlog'
            li.dropdown
              a.dropdown-toggle data-toggle="dropdown" data-target="#-"
                | Reports
                span.caret
              ul.dropdown-menu role="menu"
                li
                li
                  = link_to 'Minister report', reports_ministers_by_progress_path , :onclick=> "ga('send', 'event', 'reports', 'view', 'Minister Report')"
                li
                  = link_to 'Press desk report', reports_press_desk_by_progress_path , :onclick=> "ga('send', 'event', 'reports', 'view', 'Press Desk Report')"
            li#settings= link_to 'Settings', admin_path
            li= link_to 'Sign out', destroy_user_session_path
          = form_tag(search_path, { :method => 'get', :id => 'search_form', :class => 'navbar-form navbar-right', :role => 'search'}) do
            .form-group
              = text_field_tag :search, params[:search], { :id => 'search_field',  :class => 'form-control', :placeholder => 'Search by UIN' }
            = button_tag(:type => 'submit', :id => 'search_button', :class => 'btn btn-default') do
              span.fa.fa-search
        - elsif current_user.finance_user?
          ul.nav.navbar-nav
            li= link_to 'Sign out', destroy_user_session_path

app/views/shared/_question_assigned.html.slim
= render partial: "shared/flash_messages", flash: flash
- if question.action_officers_pqs.size > 0
  .question-allocation
    h4 Allocation:
    ul.question-allocation-list data-pqid=question.id
      - question.action_officers_pqs.each do |ao_pq|
        li
          - if !ao_pq.action_officer.nil?
            = ao_pq.action_officer.name
            | (#{ao_pq.action_officer.deputy_director.division.name})
            - if ao_pq.accepted?
              span.flag.pq-accepted Accepted
            - elsif ao_pq.rejected?
              span.flag.pq-rejected Rejected
              a.button data-target="#rejection-#{ao_pq.id}-#{ao_pq.action_officer.id}" data-toggle="collapse"
                | Display Reason
                span.caret
              .collapse id="rejection-#{ao_pq.id}-#{ao_pq.action_officer.id}"
                p
                  strong= ao_pq.reason_option
                p= ao_pq.reason
            - else
              span.flag.no-response No response

app/views/shared/_status.html.slim
.status
  - if status.deleted?
    span.fa.fa-times-circle&nbsp;
    = (defined? inactive) ? inactive : ' Inactive'
  - else
    span.fa.fa-check-circle&nbsp;
    = (defined? active) ? active : ' Active'
  

app/views/shared/_trim_link.html.slim
= render partial: "shared/flash_messages", flash: flash
- trim = question.trim_link
- if trim && !trim.deleted
  .dashboard_trim_link id="trim_links_#{trim.id}"
    = link_to('Open trim link', trim_link_path(trim), {title: 'Open trim link', rel: 'external'})
- else
  .trim-links-form id="trim-links-form-#{question.id}"
    button.button-secondary.button-choose Choose Trim file
    .tr5-message
      span.fa
      span.message
    .inline.tr5-actions.toggle-content style="overflow:hidden;"
      = form_for TrimLink.new(:pq_id => question.id),
        authenticity_token: true,
        html: { multipart: true, id: "new_trim_link_form_#{question.id}", class: 'pq-inline-form form-add-trim-link', data: {pqid: question.id }} do |f|
        = f.file_field :file_data, :class=>'pq-inline-form trim-file-chooser', :id=>"file_data-#{question.id}"
        = f.hidden_field(:pq_id , :value => question.id , :id=>"pq_id-trimlink-#{question.id}")
      button.button.button-upload Upload
      button.button.button-cancel.button-secondary Cancel

app/views/shared/_warning_icon.html.slim
span.fa.fa-exclamation-triangle title='overdue'

app/views/shared/token_invalid.html.slim
p.br.space-before-20
  strong Invalid Link

p.br.space-before
  | This link is invalid.  Please check the original email and ensure you have copied and pasted the link correctly.