config/routes.rb
ParliamentaryQuestions::Application.routes.draw do
  get 'ping'               => 'ping#index'
  get 'healthcheck'        => 'health_check#index'

  get 'statistics/'                 => 'statistics#index'
  get 'statistics/stages_time'      => 'statistics#stages_time'
  get 'statistics/on_time'          => 'statistics#on_time'
  get 'statistics/time_to_assign'   => 'statistics#time_to_assign'
  get 'statistics/ao_response_time' => 'statistics#ao_response_time'
  get 'statistics/ao_churn'         => 'statistics#ao_churn'
  get 'metrics_dashboard/'          => 'metrics_dashboard#index'
  get 'gecko_report'                => 'gecko_report#index'

  resources :minister_contacts
  get 'minister_contacts/new/:id' => 'minister_contacts#new', :as => :new_minister_contact_withid

  resources :ogds
  get 'find_ogd' => 'ogds#find'

  resources :press_desks

  resources :press_officers

  resources :progresses

  resources :ministers

  resources :deputy_directors

  resources :divisions

  resources :directorates

  resources :watchlist_members

  resources :early_bird_members

  resources :actionlist_members

  resources :action_officers

  devise_for :users, :controllers => { :invitations => 'users/invitations', sessions: 'users/sessions' }
  resources  :users

  resources :pqs, only: [ :index, :show, :update ]

  resources :trim_links

  get 'trim_links/new/:id' => 'trim_links#new'

  get 'admin' => 'admin#index'

  get 'commission/:id'               => 'commission#commission'
  get 'commission_complete/:id'      => 'commission#complete'
  get 'commission_reject_manual/:id' => 'manual_reject_commission#reject_manual'
  post 'commission'                  => 'commission#commission', as: :commission

  get 'quick_action_export'     => 'quick_action_export#new'
  post 'quick_action_export' => 'quick_action_export#new'
  get 'quick_action_export/export' => 'quick_action_export#export'

  get '/', to: 'root#index', as: :root
  get 'dashboard'             => 'dashboard#index'
  get 'dashboard/in_progress' => 'dashboard#in_progress'
  get 'dashboard/backlog' => 'dashboard#backlog'

  get 'search' => 'search#index'

  get 'filter'         => 'filter#index'
  get 'filter/:search' => 'filter#index'

  get 'dashboard/search'          => 'dashboard#search'
  post 'dashboard/search/:search' => 'dashboard#search'

  get 'dashboard/by_status/:qstatus'             => 'dashboard#by_status', as: :dashboard_by_status
  get 'dashboard/in_progress_by_status/:qstatus' => 'dashboard#in_progress_by_status', as: :dashboard_in_progress_by_status
  get 'dashboard/transferred'                    => 'dashboard#transferred', as: :dashboard_transferred
  get 'dashboard/i_will_write'                   => 'dashboard#i_will_write', as: :dashboard_iww

  get 'assignment/:uin'  => 'assignment#show', as: :assignment
  post 'assignment/:uin' => 'assignment#create'

  get 'watchlist/dashboard'   => 'watchlist_dashboard#index'
  get 'watchlist/preview'     => 'watchlist_dashboard#preview'
  get 'watchlist/send_emails' => 'watchlist_send_emails#send_emails'

  get 'early_bird/dashboard'   => 'early_bird_dashboard#index'
  get 'early_bird/preview'     => 'early_bird_dashboard#preview'
  get 'early_bird/send_emails' => 'early_bird_send_emails#send_emails'

  #get 'preview' => 'preview#index'

  get 'find_action_officers' => 'action_officers#find'

  get 'finance/questions' => 'finance#questions'
  post 'finance/confirm'  => 'finance#confirm'

  get 'transferred/new'     => 'transferred#new'
  post 'transferred/create' => 'transferred#create'

  get 'i_will_write/create' => 'i_will_write#create'

  get 'send_accept_reject_reminder/:id' => 'action_officer_reminder#accept_reject'
  get 'send_draft_reminder/:id'         => 'action_officer_reminder#send_draft'

  match 'export/pq.csv' => 'export#csv', via: [:get, :post]
  get 'export'          => 'export#index'

  match 'export_pod/pq_pod.csv' => 'export#csv_for_pod', via: [:get, :post]
  get 'export_pod'              => 'export#index_for_pod'

  match 'export/csv_quick.csv' => 'export#csv_quick', via: [:get, :post]
  get 'export'          => 'export#index'

  get 'reports/ministers_by_progress'  => 'reports#ministers_by_progress'
  get 'reports/press_desk_by_progress' => 'reports#press_desk_by_progress'
  match 'reports/filter_all'           => 'reports#filter_all', via: [:get, :post], as: 'filter_all'
  if Rails.env.development?
    mount_rails_db_info as: 'rails_db_info_engine'
    # mount_rails_db_info is enough for rails version < 4
  end
  match "*path", to: "application#page_not_found", via: :all

  if Rails.env.production?
    get '401', :to => 'application#unauthorized'
    get '404', :to => 'application#page_not_found'
    get '500', :to => 'application#server_error'
  end
end

app/models/press_officer.rb
# == Schema Information
#
# Table name: press_officers
#
#  id            :integer          not null, primary key
#  name          :string(255)
#  email         :string(255)
#  press_desk_id :integer
#  deleted       :boolean          default(FALSE)
#  created_at    :datetime
#  updated_at    :datetime
#

class PressOfficer < ActiveRecord::Base
  extend  SoftDeletion::Collection
  include SoftDeletion::Record

  has_paper_trail
  validates :name, presence: true
  validates_format_of :email,:with => Devise::email_regexp
  validates :press_desk_id, presence: true
  belongs_to :press_desk
end

app/controllers/press_officers_controller.rb
class PressOfficersController < ApplicationController
  before_action :authenticate_user!, PQUserFilter
  before_action :set_press_officer, only: [:show, :edit, :update, :destroy]
  before_action :prepare_press_offices

  def index
    @press_officers = PressOfficer.order('lower(name)')
    update_page_title('Press officers')
  end

  def new
    @press_officer = PressOfficer.new
    update_page_title('Add press officer')
  end

  def show
    update_page_title('Press officer details')
  end

  def edit
    update_page_title('Edit press officer')
  end


  def create
    @press_officer = PressOfficer.new(press_officer_params)

    if @press_officer.save
      flash[:success] = 'Press officer was successfully created.'
      redirect_to @press_officer
    else
      render action: 'new'
    end
  end

  def update
    if @press_officer.update(press_officer_params)
      flash[:success] = 'Press officer was successfully updated.'
      redirect_to @press_officer
    else
      render action: 'edit'
    end
  end

  private

  def set_press_officer
    @press_officer = PressOfficer.find(params[:id])
  end

  def press_officer_params
    params.require(:press_officer).permit(:name, :email, :press_desk_id, :deleted)
  end

  def prepare_press_offices
    @press_offices = PressDesk.active
  end
end

app/views/press_officers/_form.html.slim
#admin-po-form
  = form_for(@press_officer) do |f|
    = render partial: 'shared/errors', object: @press_officer
    fieldset
      .form-group
        label.form-label for="press_officer_name"  Name
        = f.text_field :name, {class: 'form-control'}
      .form-group
        label.form-label for="press_officer_email"  Email
        = f.email_field :email, {class: 'form-control'}
      .form-group
        label.form-label for="press_officer_press_desk_id"  Press Desk
        = f.collection_select(:press_desk_id, @press_offices, :id, :name, :include_blank => "Please select")
      .form-group
        p.text Status
        label.block-label for="press_officer_deleted"
          = f.check_box :deleted
          | Inactive
      .form-group
        = f.submit 'Save', :id => 'save', :class => 'button'

app/views/press_officers/edit.html.slim
h1 Edit press officer
= render 'form'
= link_to 'Return to press officer list', press_officers_path, {class: 'admin-link'}

app/views/press_officers/index.html.slim
#admin-po-list
  h1 Press officers
  div class="row"
    ul#admin-button-bar
      li= link_to ('Add press officer'), new_press_officer_path, {class: 'button-secondary'}
  table.table
    thead
      tr
        th Name
        th Press Desk
        th#admin-status Status
        th
    tbody
      - @press_officers.each do |press_officer|
        tr
          td= link_to press_officer.name, press_officer_path(press_officer)
          td= press_officer.press_desk.name
          td= render partial: 'shared/status', object: press_officer
          td.edit= link_to 'Edit', edit_press_officer_path(press_officer)

app/views/press_officers/new.html.slim
h1 Add press officer
= render 'form'
= link_to 'Return to press officer list', press_officers_path, {class: 'admin-link'}

app/views/press_officers/show.html.slim
h1 Press officer details
#admin-po-details
  = render partial: "shared/flash_messages", flash: flash
  h2 Name
  p.text= @press_officer.name
  h2 Email
  p.text= @press_officer.email
  h2 Status
  = render partial: 'shared/status', object: @press_officer
  = link_to 'Edit', edit_press_officer_path(@press_officer), {class: 'admin-link'}
  = link_to 'Return to press officer list', press_officers_path, {class: 'admin-link'}