config/routes.rb
ParliamentaryQuestions::Application.routes.draw do
  get 'ping'               => 'ping#index'
  get 'healthcheck'        => 'health_check#index'

  get 'statistics/'                 => 'statistics#index'
  get 'statistics/stages_time'      => 'statistics#stages_time'
  get 'statistics/on_time'          => 'statistics#on_time'
  get 'statistics/time_to_assign'   => 'statistics#time_to_assign'
  get 'statistics/ao_response_time' => 'statistics#ao_response_time'
  get 'statistics/ao_churn'         => 'statistics#ao_churn'
  get 'metrics_dashboard/'          => 'metrics_dashboard#index'
  get 'gecko_report'                => 'gecko_report#index'

  resources :minister_contacts
  get 'minister_contacts/new/:id' => 'minister_contacts#new', :as => :new_minister_contact_withid

  resources :ogds
  get 'find_ogd' => 'ogds#find'

  resources :press_desks

  resources :press_officers

  resources :progresses

  resources :ministers

  resources :deputy_directors

  resources :divisions

  resources :directorates

  resources :watchlist_members

  resources :early_bird_members

  resources :actionlist_members

  resources :action_officers

  devise_for :users, :controllers => { :invitations => 'users/invitations', sessions: 'users/sessions' }
  resources  :users

  resources :pqs, only: [ :index, :show, :update ]

  resources :trim_links

  get 'trim_links/new/:id' => 'trim_links#new'

  get 'admin' => 'admin#index'

  get 'commission/:id'               => 'commission#commission'
  get 'commission_complete/:id'      => 'commission#complete'
  get 'commission_reject_manual/:id' => 'manual_reject_commission#reject_manual'
  post 'commission'                  => 'commission#commission', as: :commission

  get 'quick_action_export'     => 'quick_action_export#new'
  post 'quick_action_export' => 'quick_action_export#new'
  get 'quick_action_export/export' => 'quick_action_export#export'

  get '/', to: 'root#index', as: :root
  get 'dashboard'             => 'dashboard#index'
  get 'dashboard/in_progress' => 'dashboard#in_progress'
  get 'dashboard/backlog' => 'dashboard#backlog'

  get 'search' => 'search#index'

  get 'filter'         => 'filter#index'
  get 'filter/:search' => 'filter#index'

  get 'dashboard/search'          => 'dashboard#search'
  post 'dashboard/search/:search' => 'dashboard#search'

  get 'dashboard/by_status/:qstatus'             => 'dashboard#by_status', as: :dashboard_by_status
  get 'dashboard/in_progress_by_status/:qstatus' => 'dashboard#in_progress_by_status', as: :dashboard_in_progress_by_status
  get 'dashboard/transferred'                    => 'dashboard#transferred', as: :dashboard_transferred
  get 'dashboard/i_will_write'                   => 'dashboard#i_will_write', as: :dashboard_iww

  get 'assignment/:uin'  => 'assignment#show', as: :assignment
  post 'assignment/:uin' => 'assignment#create'

  get 'watchlist/dashboard'   => 'watchlist_dashboard#index'
  get 'watchlist/preview'     => 'watchlist_dashboard#preview'
  get 'watchlist/send_emails' => 'watchlist_send_emails#send_emails'

  get 'early_bird/dashboard'   => 'early_bird_dashboard#index'
  get 'early_bird/preview'     => 'early_bird_dashboard#preview'
  get 'early_bird/send_emails' => 'early_bird_send_emails#send_emails'

  #get 'preview' => 'preview#index'

  get 'find_action_officers' => 'action_officers#find'

  get 'finance/questions' => 'finance#questions'
  post 'finance/confirm'  => 'finance#confirm'

  get 'transferred/new'     => 'transferred#new'
  post 'transferred/create' => 'transferred#create'

  get 'i_will_write/create' => 'i_will_write#create'

  get 'send_accept_reject_reminder/:id' => 'action_officer_reminder#accept_reject'
  get 'send_draft_reminder/:id'         => 'action_officer_reminder#send_draft'

  match 'export/pq.csv' => 'export#csv', via: [:get, :post]
  get 'export'          => 'export#index'

  match 'export_pod/pq_pod.csv' => 'export#csv_for_pod', via: [:get, :post]
  get 'export_pod'              => 'export#index_for_pod'

  match 'export/csv_quick.csv' => 'export#csv_quick', via: [:get, :post]
  get 'export'          => 'export#index'

  get 'reports/ministers_by_progress'  => 'reports#ministers_by_progress'
  get 'reports/press_desk_by_progress' => 'reports#press_desk_by_progress'
  match 'reports/filter_all'           => 'reports#filter_all', via: [:get, :post], as: 'filter_all'
  if Rails.env.development?
    mount_rails_db_info as: 'rails_db_info_engine'
    # mount_rails_db_info is enough for rails version < 4
  end
  match "*path", to: "application#page_not_found", via: :all

  if Rails.env.production?
    get '401', :to => 'application#unauthorized'
    get '404', :to => 'application#page_not_found'
    get '500', :to => 'application#server_error'
  end
end

app/models/minister.rb
# == Schema Information
#
# Table name: ministers
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  title      :string(255)
#  deleted    :boolean          default(FALSE)
#  created_at :datetime
#  updated_at :datetime
#  member_id  :integer
#

class Minister < ActiveRecord::Base
  extend  SoftDeletion::Collection
  include SoftDeletion::Record

  has_paper_trail
  before_validation :strip_whitespace!

  has_many :pqs
  has_many :minister_contacts
  accepts_nested_attributes_for :minister_contacts,
                                :allow_destroy => true,
                                :reject_if     => :all_blank

  def contact_emails
    minister_contacts.active.pluck('email')
  end

  def name_with_inactive_status
    self.name + (self.deleted ? ' - Inactive' : '')
  end

  def self.active_or_having_id(minister_id = nil)
    table = Minister.arel_table
    arel = table[:deleted].eq(false)
    arel = arel.or(table[:id].eq(minister_id)) if minister_id
    where(arel)
  end

  private

  def strip_whitespace!
    self.name = self.name.strip if self.name
  end
end

app/controllers/ministers_controller.rb
class MinistersController < ApplicationController
  before_action :authenticate_user!, PQUserFilter
  before_action :set_minister, only: [:show, :edit, :update, :destroy]

  def index
    @ministers = Minister.order('lower(name)')
    update_page_title('Ministers')
  end

  def show
    @minister_contacts = @minister.minister_contacts
    update_page_title('Minister details')
  end

  def new
    @minister = Minister.new
    @minister.minister_contacts << MinisterContact.new
    update_page_title('Add minister')
  end

  def edit
    update_page_title('Edit minister')
  end

  def create
    @minister = Minister.new(minister_params)
    if @minister.save
      flash[:success] = 'Minister was successfully created.'
      redirect_to @minister
    else
      render action: 'new'
    end
  end

  def update
    if @minister.update(minister_params)
      flash[:success] = 'Minister was successfully updated.'
      redirect_to @minister
    else
      render action: 'edit'
    end
  end

  private

  def set_minister
    @minister = Minister.find(params[:id])
  end

  def minister_params
    params.require(:minister).permit(:name, :title, :email, :deleted, :member_id, minister_contacts_attributes: [ :id, :name, :email, :phone, :deleted, :minister_id ])
  end
end

app/views/ministers/_form.html.slim
#admin-minister-form
  = form_for(@minister) do |f|
    = render partial: 'shared/errors', object: @minister
    fieldset
      .form-group
        label.form-label for="minister_name"  Name
        = f.text_field :name, {class: 'form-control'}
      .form-group
        label.form-label for="minister_title"  Title
        = f.text_field :title, {class: 'form-control'}
      = f.fields_for :minister_contacts do |ff|
        .form-group
          label.form-label for="minister_minister_contacts_attributes_0_name"  Contact description
          = ff.text_field :name, {class: 'form-control'}
        .form-group
          label.form-label for="minister_minister_contacts_attributes_0_email"  Email
          = ff.email_field :email, {class: 'form-control'}
        .form-group
          label.form-label for="minister_minister_contacts_attributes_0_phone"  Phone
          = ff.text_field :phone, {class: 'form-control'}
        .form-group
          p.text Contact status
          label.block-label for="minister_minister_contacts_attributes_0_deleted"
            = ff.check_box :deleted
            | Inactive
      .form-group
        p.text style=""  Minister status
        label.block-label for="minister_deleted"
          = f.check_box :deleted
          = ' Inactive'
      .form-group
        = f.submit 'Save', :id => 'save', :class => 'button'

app/views/ministers/edit.html.slim
h1 Edit minister
= render 'form'
= link_to 'Return to Minister list', ministers_path, {class: 'admin-link'}

app/views/ministers/index.html.slim
h1 Ministers
#admin-ministers-list
  div class="row"
    ul#admin-button-bar
      li= link_to ('Add minister'), new_minister_path, {class: 'button-secondary'}
  table.table
    thead
      tr
        th#minister-name Name
        th Title
        th#admin-status Status
        th
    tbody
      - @ministers.each do |minister|
        tr
          td= link_to minister.name, minister_path(minister)
          td= minister.title
          td= render partial: 'shared/status', object: minister
          td.edit= link_to 'Edit', edit_minister_path(minister)

app/views/ministers/new.html.slim
h1 Add minister
= render 'form'
= link_to 'Return to minister list', ministers_path, {class: 'admin-link'}

app/views/ministers/show.html.slim
#admin-ministers-details
  h1 Minister details
  = render partial: "shared/flash_messages", flash: flash
  h2 Name
  p.text= @minister.name
  h2 Title
  p.text= @minister.title
  h2 Status
  = render partial: 'shared/status', object: @minister
  h2 Contacts
  div class="row"
    ul#admin-button-bar
      li= link_to ('Add new contact'), new_minister_contact_withid_path(@minister), {class: 'button-secondary'}
  table.table
    thead
      tr
        th Description
        th email
        th phone
        th#admin-status Status
        th
    tbody
      - @minister_contacts.each do |c|
        tr
          td= link_to c.name, edit_minister_contact_path(c)
          td= c.email
          td= c.phone
          td= render partial: 'shared/status', object: c
          td.edit= link_to 'Edit', edit_minister_contact_path(c)
  = link_to 'Return to the minister list', ministers_path, {class: 'admin-link'}